---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    sslh_fqdn: server.example.com
  tasks:
    - name: Include role 'ansible-role-sslh'
      ansible.builtin.include_role:
        name: ansible-role-sslh
