---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    sslh_fqdn: server.example.com
  tasks:
    - name: Include role 'ansible-role-sslh'
      include_role:
        name: ansible-role-sslh
